name: hello-world
on:
  push

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Print Hello World File Content
        run: cat hello-world.txt

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm ci

      - name: Build the Project
        run: npm run build --if-present

      - name: Run Tests
        run: npm test
