name: hello-world
on:
  push

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
     - name: checkout repository code
       uses: actions/checkout@v3

     - name: print hello-world text  
       run: echo "$(cat hello-world.txt)"  